DROP DATABASE IF EXISTS guessTheNumberDB;
CREATE DATABASE guessTheNumberDB;

USE guessTheNumberDB;

CREATE TABLE Game (
	id SMALLINT UNSIGNED PRIMARY KEY,
    answer SMALLINT UNSIGNED NOT NULL,
    status CHAR(12)
);

CREATE TABLE Round (
	id SMALLINT UNSIGNED PRIMARY KEY NOT NULL,
    gameId SMALLINT UNSIGNED NOT NULL,
    timePlaced DATETIME DEFAULT CURRENT_TIMESTAMP,
    guess CHAR(4) NOT NULL,
    exactMatches TINYINT,
    partialMatches TINYINT,
    FOREIGN KEY (gameId) REFERENCES Game(id)
)